{
	"version": 1501895612,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/vaquinha-sheet0.png",
		"images/vaquinha-sheet1.png",
		"images/churrasqueira-sheet0.png",
		"images/fumaca.png",
		"images/gameover-sheet0.png",
		"images/iniciar.png",
		"images/blocoplay-sheet0.png",
		"images/cenario-sheet0.png",
		"images/madeirachao-sheet0.png",
		"images/madeirasuportechao-sheet0.png",
		"images/chaocalcada-sheet0.png",
		"images/refletirvaca-sheet0.png",
		"images/selecionarfase-sheet0.png",
		"images/selecionarfase-sheet1.png",
		"images/selecionarfase-sheet2.png",
		"images/vitoriacolision2-sheet0.png",
		"images/pedaçosvacas-sheet0.png",
		"images/areaclick-sheet0.png",
		"images/retry-sheet0.png",
		"images/passou-sheet0.png",
		"images/cenario2-sheet0.png",
		"images/pontaesquerda-sheet0.png",
		"images/resetlevels-sheet0.png",
		"images/passoulevel-sheet0.png",
		"images/menujogo-sheet0.png",
		"media/pulo1.m4a",
		"media/pulo1.ogg",
		"media/moon (mp3cut.net).m4a",
		"media/moon (mp3cut.net).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}