{
	"version": 1502000279,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/vaquinha-sheet0.png",
		"images/vaquinha-sheet1.png",
		"images/churrasqueira-sheet0.png",
		"images/fumaca.png",
		"images/gameover-sheet0.png",
		"images/iniciar.png",
		"images/cenario-sheet0.png",
		"images/madeirachao-sheet0.png",
		"images/madeirasuportechao-sheet0.png",
		"images/chaocalcada-sheet0.png",
		"images/refletirvaca-sheet0.png",
		"images/selecionarfase-sheet0.png",
		"images/selecionarfase-sheet1.png",
		"images/vitoriacolision2-sheet0.png",
		"images/pedaçosvacas-sheet0.png",
		"images/areaclick-sheet0.png",
		"images/retry-sheet0.png",
		"images/passou-sheet0.png",
		"images/cenario2-sheet0.png",
		"images/pontaesquerda-sheet0.png",
		"images/iinvert-sheet0.png",
		"images/resetlevels-sheet0.png",
		"images/passoulevel-sheet0.png",
		"images/menujogo-sheet0.png",
		"images/fogochurrasqueira.png",
		"images/botãoplay-sheet0.png",
		"images/fundotelas-sheet0.png",
		"images/botaomenu-sheet0.png",
		"images/botaoproxfase-sheet0.png",
		"images/botaomusic-sheet0.png",
		"images/botaomusic-sheet1.png",
		"images/telavoceperdeu-sheet0.png",
		"images/creditos-sheet0.png",
		"media/pulo1.m4a",
		"media/pulo1.ogg",
		"media/moon (mp3cut.net).m4a",
		"media/moon (mp3cut.net).ogg",
		"media/single cow-soundbible.com-2051754137-[audiotrimmer.com].m4a",
		"media/single cow-soundbible.com-2051754137-[audiotrimmer.com].ogg",
		"media/woosh-mark_diangelo-4778593 (online-audio-converter.com).m4a",
		"media/woosh-mark_diangelo-4778593 (online-audio-converter.com).ogg",
		"media/buttonclick.ogg",
		"media/theme.ogg",
		"media/theme2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}