{
	"version": 1543102761,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/borda1-sheet0.png",
		"images/lifep1-sheet0.png",
		"images/fundoboxe-sheet0.png",
		"images/lutadorboxe1-sheet0.png",
		"images/lutadorboxe1-sheet1.png",
		"images/limitering-sheet0.png",
		"images/lutadorboxe2-sheet0.png",
		"images/lutadorboxe2-sheet1.png",
		"images/chão-sheet0.png",
		"images/personagem1-sheet0.png",
		"images/personagem2-sheet0.png",
		"images/selecioneseupersonagem-sheet0.png",
		"images/fundo1-sheet0.png",
		"images/setavoltar-sheet0.png",
		"images/fundo2-sheet0.png",
		"images/controle-sheet0.png",
		"images/jogar-sheet0.png",
		"images/fade-sheet0.png",
		"images/fundo4-sheet0.png",
		"images/thefiveplayerslogo-sheet0.png",
		"images/alcides-sheet0.png",
		"images/fundoc-sheet0.png",
		"images/isaac-sheet0.png",
		"images/jacó-sheet0.png",
		"images/nathan-sheet0.png",
		"images/wallace-sheet0.png",
		"images/pjd2v-sheet0.png",
		"images/boneco1telainicial-sheet0.png",
		"images/boneco2telainicial-sheet0.png",
		"images/boneco2telainicial-sheet1.png",
		"images/botãoplay-sheet0.png",
		"images/botãoplay-sheet1.png",
		"images/títuloboxe-sheet0.png",
		"images/botãosom-sheet0.png",
		"images/botãosom-sheet1.png",
		"images/botãocréditos-sheet0.png",
		"media/som jogando boxe.ogg",
		"media/som escolha de luta.ogg",
		"media/som soco.ogg",
		"media/som seleção de personagem de boxe.ogg",
		"media/dano sofrido.ogg",
		"media/3, 2 ,1 go!.ogg",
		"media/you lose.ogg",
		"media/you win.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}