{
	"version": 1572223052,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/botãoconfiguração-sheet0.png",
		"images/botãomúsica-sheet0.png",
		"images/botãomúsica-sheet1.png",
		"images/botãoreiniciar-sheet0.png",
		"images/botãoplay-sheet0.png",
		"images/botãosom-sheet0.png",
		"images/botãosom-sheet1.png",
		"images/botãocréditos-sheet0.png",
		"images/botãox-sheet0.png",
		"images/menu-sheet0.png",
		"images/telagamerover-sheet0.png",
		"images/telapause-sheet0.png",
		"images/seta-sheet0.png",
		"images/seta2-sheet0.png",
		"images/botãopulartutorial-sheet0.png",
		"images/cangurucf2-sheet0.png",
		"images/cangurucf2-sheet1.png",
		"images/cangurusf-sheet0.png",
		"images/cangurusf-sheet1.png",
		"images/lobo-sheet0.png",
		"images/lobo-sheet1.png",
		"images/lobo-sheet2.png",
		"images/piranha-sheet0.png",
		"images/pássaro-sheet0.png",
		"images/paredelobo-sheet0.png",
		"images/limitepiranhabaixo-sheet0.png",
		"images/cangurutut-sheet0.png",
		"images/cangurutut-sheet1.png",
		"images/filhote-sheet0.png",
		"images/filhote-sheet1.png",
		"images/filhote-sheet2.png",
		"images/danoaltura-sheet0.png",
		"images/troncocaindo-sheet0.png",
		"images/carro-sheet0.png",
		"images/carro-sheet1.png",
		"images/cangurufinal-sheet0.png",
		"images/cangurufinal-sheet1.png",
		"images/limitefinal-sheet0.png",
		"images/troncofumaça-sheet0.png",
		"images/cangurucf-sheet0.png",
		"images/cangurucf-sheet1.png",
		"images/mira-sheet0.png",
		"images/pássarofinal-sheet0.png",
		"images/bananacoletável-sheet0.png",
		"images/bananabullet-sheet0.png",
		"images/maçã-sheet0.png",
		"images/maçãexplic-sheet0.png",
		"images/primeirauva-sheet0.png",
		"images/maçãpodreexplic-sheet0.png",
		"images/maçãdourada-sheet0.png",
		"images/frascobanana-sheet0.png",
		"images/frascouva-sheet0.png",
		"images/uvaexplic-sheet0.png",
		"images/fase1tf-sheet0.png",
		"images/fase1tf-sheet1.png",
		"images/fase2tf-sheet0.png",
		"images/fase2tf-sheet1.png",
		"images/fase3tf-sheet0.png",
		"images/fase3tf-sheet1.png",
		"images/fundofases-sheet0.png",
		"images/fundotelainicial-sheet0.png",
		"images/fundofloresta-sheet0.png",
		"images/fundotelacréditos-sheet0.png",
		"images/fundo-sheet0.png",
		"images/fundodafase-sheet0.png",
		"images/coraçãovida-sheet0.png",
		"images/coraçãovida-sheet1.png",
		"images/thefiveplayerslogo-sheet0.png",
		"images/chão-sheet0.png",
		"images/chãofinalf3-sheet0.png",
		"images/plataformafirme-sheet0.png",
		"images/chãotutorial.png",
		"images/chãofinalizartut-sheet0.png",
		"images/lama.png",
		"images/tronco2-sheet0.png",
		"images/tronco3-sheet0.png",
		"images/blocolayout-sheet0.png",
		"images/plataforma1-sheet0.png",
		"images/plataforma4-sheet0.png",
		"images/plataforma6-sheet0.png",
		"images/plataforma9-sheet0.png",
		"images/plataforma5-sheet0.png",
		"images/plataforma8-sheet0.png",
		"images/plataforma7-sheet0.png",
		"images/plataforma10-sheet0.png",
		"images/plataforma12-sheet0.png",
		"images/plataforma13-sheet0.png",
		"images/plataforma14-sheet0.png",
		"images/plataforma15-sheet0.png",
		"images/plataforma16-sheet0.png",
		"images/plataforma23.png",
		"images/plataforma21.png",
		"images/plataforma28.png",
		"images/plataforma29.png",
		"images/plataforma32.png",
		"images/plataforma33.png",
		"images/lama2.png",
		"images/plataforma39.png",
		"images/chãofinal-sheet0.png",
		"images/buraco-sheet0.png",
		"images/rio.png",
		"images/plataformafixagrande-sheet0.png",
		"images/plataformafixapequena-sheet0.png",
		"images/troncotremulento-sheet0.png",
		"images/tiledbackground.png",
		"images/placaperigo-sheet0.png",
		"images/fimtutorial-sheet0.png",
		"images/arbusto-sheet0.png",
		"images/copaarvor-sheet0.png",
		"images/coqueiro-sheet0.png",
		"images/copaarvor2-sheet0.png",
		"images/tronco-sheet0.png",
		"images/rocha-sheet0.png",
		"images/Árvorecenainício-sheet0.png",
		"images/chave-sheet0.png",
		"images/gruta-sheet0.png",
		"images/tronco4-sheet0.png",
		"images/arvore-sheet0.png",
		"images/pedra-sheet0.png",
		"images/broto-sheet0.png",
		"images/broto-sheet1.png",
		"images/casafinal-sheet0.png",
		"images/copa-sheet0.png",
		"images/folhas-sheet0.png",
		"images/folhas2-sheet0.png",
		"images/copa2-sheet0.png",
		"images/copa3-sheet0.png",
		"images/copa4-sheet0.png",
		"images/galhoespecialtut-sheet0.png",
		"images/Árvorequeimada-sheet0.png",
		"images/setaverde-sheet0.png",
		"images/balãofala-sheet0.png",
		"images/símboloaviso-sheet0.png",
		"images/cangurupensamento-sheet0.png",
		"images/nuvempensamento-sheet0.png",
		"images/portalfinalf3-sheet0.png",
		"images/buracolama-sheet0.png",
		"images/setaverde2-sheet0.png",
		"images/fundodealcides-sheet0.png",
		"images/fundodealcides2-sheet0.png",
		"images/arvoreteste2-sheet0.png",
		"images/arvoreteste-sheet0.png",
		"images/automacaoemnuvem-sheet0.png",
		"images/finalf2-sheet0.png",
		"images/coqueiro3-sheet0.png",
		"images/cachoeira-sheet0.png",
		"images/explicaçãocontroles-sheet0.png",
		"images/inimigoatordoado-sheet0.png",
		"images/doublejump-sheet0.png",
		"images/poção-sheet0.png",
		"images/premiação-sheet0.png",
		"images/setapulo-sheet0.png",
		"images/setasmovimentos-sheet0.png",
		"images/mousetutorial2-sheet0.png",
		"images/explicaçãomaçãpodre-sheet0.png",
		"images/cigarro-sheet0.png",
		"images/cigarro-sheet1.png",
		"images/pista-sheet0.png",
		"images/fade-sheet0.png",
		"images/fundopreto-sheet0.png",
		"images/desmaiou-sheet0.png",
		"images/pqp-sheet0.png",
		"images/bb-sheet0.png",
		"media/som pulo.ogg",
		"media/som clique mouse.ogg",
		"media/sommaçãestragada.ogg",
		"media/somfrutaboa.ogg",
		"media/som carro2.ogg",
		"media/som dano.ogg",
		"media/somjogandobanana.ogg",
		"media/som lose.ogg",
		"media/som win.ogg",
		"media/som fasetrancada.ogg",
		"media/som fase destrancada.ogg",
		"media/som vidaextra_chave.ogg",
		"media/som se cair no riacho.ogg",
		"media/som Árvore rachando.ogg",
		"media/somgrito.ogg",
		"media/somfogocigarro.ogg",
		"media/somfogofloresta.ogg",
		"media/som falapássaro.ogg",
		"media/somsuspensef1.ogg",
		"media/música tela inicial.ogg",
		"media/música fase 1.ogg",
		"media/música fase 2.ogg",
		"media/música fase 3.ogg",
		"media/música tutorial.ogg",
		"media/música floresta.ogg",
		"media/música telacréditos.ogg",
		"media/músicacenafinal.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}