{
	"version": 1544791582,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/playercontroller-sheet0.png",
		"images/chao-sheet0.png",
		"images/botao_movimento-sheet0.png",
		"images/botao_movimento-sheet1.png",
		"images/spritefont.png",
		"images/btn_play-sheet0.png",
		"images/btn_play-sheet1.png",
		"images/inimigo-sheet0.png",
		"images/inimigo-sheet1.png",
		"images/parede_inimigo-sheet0.png",
		"images/btn_pause-sheet0.png",
		"images/btn_pause-sheet1.png",
		"images/menu_opcoes-sheet0.png",
		"images/btn_return-sheet0.png",
		"images/btn_return-sheet1.png",
		"images/img_vida-sheet0.png",
		"images/personagem-sheet0.png",
		"images/agua_chao-sheet0.png",
		"images/bolha-sheet0.png",
		"images/bolha-sheet1.png",
		"images/destruir_bolhas-sheet0.png",
		"images/ceu_limpo-sheet0.png",
		"images/nuvem-sheet0.png",
		"images/areia_chao-sheet0.png",
		"images/cidade-sheet0.png",
		"images/img_persona-sheet0.png",
		"images/img_gotinha-sheet0.png",
		"images/img_gotinha-sheet1.png",
		"images/img_gotinha-sheet2.png",
		"images/terra_coletada-sheet0.png",
		"images/tiledbackground.png",
		"images/trator-sheet0.png",
		"images/trator-sheet1.png",
		"images/trator-sheet2.png",
		"images/barreira-sheet0.png",
		"images/barreira-sheet1.png",
		"images/logo-sheet0.png",
		"images/rio-sheet0.png",
		"images/select_level-sheet0.png",
		"images/select_level-sheet1.png",
		"images/clearstorage-sheet0.png",
		"images/concluida_fase-sheet0.png",
		"images/btn_conf-sheet0.png",
		"images/btn_conf-sheet1.png",
		"images/placa-sheet0.png",
		"images/n_fase-sheet0.png",
		"images/objetivo_trator-sheet0.png",
		"images/arvore-sheet0.png",
		"images/barco-sheet0.png",
		"images/rio_transp-sheet0.png",
		"images/lixo-sheet0.png",
		"images/lixo-sheet1.png",
		"images/perder_vida_lixo-sheet0.png",
		"images/lixo_col-sheet0.png",
		"images/fundolixo-sheet0.png",
		"images/objetivo_lix-sheet0.png",
		"images/powerup-sheet0.png",
		"images/powerup-sheet1.png",
		"images/chao_fase5-sheet0.png",
		"images/predadores_fase5-sheet0.png",
		"images/bala_predadores-sheet0.png",
		"images/alavanca_fecharcomporta-sheet0.png",
		"images/bandeira-sheet0.png",
		"images/animacao_lixo-sheet0.png",
		"images/simbolo_lixo-sheet0.png",
		"images/chao_fase-sheet0.png",
		"images/fundo_ceu-sheet0.png",
		"images/chao_tiled.png",
		"images/agua_fase5-sheet0.png",
		"images/tiledbackground2.png",
		"images/pararagua-sheet0.png",
		"images/nome_jogo-sheet0.png",
		"images/tiled_morros.png",
		"images/concreto-sheet0.png",
		"images/barreira_conct-sheet0.png",
		"images/fundo_select_fases-sheet0.png",
		"images/tiledbackground3.png",
		"images/fundo_opc-sheet0.png",
		"images/fundo-sheet0.png",
		"images/btn_msc-sheet0.png",
		"images/btn_msc-sheet1.png",
		"images/btn_efectsounds-sheet0.png",
		"images/btn_efectsounds-sheet1.png",
		"images/btn_fechar-sheet0.png",
		"images/btn_fechar-sheet1.png",
		"images/derrotado-sheet0.png",
		"images/text_vitoria-sheet0.png",
		"images/txt_derrota-sheet0.png",
		"images/btn_menu-sheet0.png",
		"images/btn_menu-sheet1.png",
		"images/torre-sheet0.png",
		"images/fundo_logo-sheet0.png",
		"images/matar_baixo-sheet0.png",
		"images/gastoxico.png",
		"images/canoscomportas-sheet0.png",
		"images/canoscomportas-sheet1.png",
		"images/ligaedesligacomporta-sheet0.png",
		"images/cria_inimigos-sheet0.png",
		"images/botaoselectlevel-sheet0.png",
		"images/botaoselectlevel-sheet1.png",
		"images/btn_cred-sheet0.png",
		"images/btn_cred-sheet1.png",
		"images/creditos-sheet0.png",
		"images/btn_info-sheet0.png",
		"images/btn_info-sheet1.png",
		"images/instruçoes-sheet0.png",
		"images/varadepescaeenxada-sheet0.png",
		"images/varadepescaeenxada2-sheet0.png",
		"images/passar_fase_destroy-sheet0.png",
		"images/btn_avancar-sheet0.png",
		"images/btn_avancar-sheet1.png",
		"images/sombalançarterra-sheet0.png",
		"images/inimigo2-sheet0.png",
		"images/inimigo2-sheet1.png",
		"images/setatrator-sheet0.png",
		"media/andando.m4a",
		"media/andando.ogg",
		"media/coletar2.m4a",
		"media/coletar2.ogg",
		"media/morrer.m4a",
		"media/morrer.ogg",
		"media/passar de fase.m4a",
		"media/passar de fase.ogg",
		"media/perdeu.m4a",
		"media/perdeu.ogg",
		"media/alavanca.ogg",
		"media/correndo2.ogg",
		"media/dano no tiro.ogg",
		"media/ganhou.ogg",
		"media/clique.m4a",
		"media/clique.ogg",
		"media/clique2.m4a",
		"media/clique2.ogg",
		"media/clique3 (online-audio-converter.com).m4a",
		"media/clique3 (online-audio-converter.com).ogg",
		"media/bolha.m4a",
		"media/bolha.ogg",
		"media/dano.m4a",
		"media/dano.ogg",
		"media/credits.m4a",
		"media/credits.ogg",
		"media/dano2.m4a",
		"media/dano2.ogg",
		"media/logo.m4a",
		"media/logo.ogg",
		"media/lixo na agua.m4a",
		"media/lixo na agua.ogg",
		"media/pulo.m4a",
		"media/pulo.ogg",
		"media/cair.m4a",
		"media/pulo2.ogg",
		"media/enemydestroy.m4a",
		"media/coletando power.m4a",
		"media/coletando power.ogg",
		"media/coletar lixo.m4a",
		"media/coletar lixo.ogg",
		"media/enemydestroy.ogg",
		"media/trampolim.m4a",
		"media/trampolim.ogg",
		"media/balançando terra.m4a",
		"media/balançando terra.ogg",
		"media/destruindo barreira.m4a",
		"media/destruindo barreira.ogg",
		"media/morrer2.m4a",
		"media/morrer2.ogg",
		"media/fundo 2.m4a",
		"media/fundo 2.ogg",
		"media/tentativa de fundo.m4a",
		"media/tentativa de fundo.ogg",
		"media/creditos.m4a",
		"media/creditos.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}